### Local variable
@urlLocal = {{apiUrl}}/auth
@contentType = application/json

### Login
# @name login
POST {{urlLocal}}/login
Content-Type: {{contentType}}

{
    "email": "example@provider.com",
    "password": "123456"
}

###

# @authToken = {{login.response.headers.X-AuthToken}}

### Register
POST {{urlLocal}}/register
Content-Type: {{contentType}}

{
    "name": "example",
    "email": "example@provider.com",
    "password": "123456"
}


### Check-token

POST {{urlLocal}}/check-token
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImV4YW1wbGUiLCJlbWFpbCI6ImV4YW1wbGVAcHJvdmlkZXIuY29tIiwiaWF0IjoxNzI0MTY3ODQxLCJleHAiOjE3MjQ3NzI2NDEsImF1ZCI6InVzZXJzIiwiaXNzIjoibG9naW4iLCJzdWIiOiIxIn0.HDGeG2oLtdy1dAug1GOTOCMo44BUHzAz6Nkub9y9S-Q

{
  
}