### Local variable
@urlLocal = {{apiUrl}}/auth
@contentType = application/json

### Login
# @name login
POST {{urlLocal}}/login
Content-Type: {{contentType}}

{
    "email": "eng.mykael@gmail.com",
    "password": "123456"
}

###

# @authToken = {{login.response.headers.X-AuthToken}}

### Register
POST {{urlLocal}}/register
Content-Type: {{contentType}}

{
    "name": "Mykael",
    "email": "eng.mykael@gmail.com",
    "password": "123456"
}

### Forget
POST {{urlLocal}}/forget
Content-Type: {{contentType}}

{
    "email": "eng3.mykael@gmail.com"
}

### Reset
POST {{urlLocal}}/reset
Content-Type: {{contentType}}

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTcyNDI2ODM0NywiZXhwIjoxNzI0MjcwMTQ3LCJhdWQiOiJ1c2VycyIsImlzcyI6ImZvcmdldCIsInN1YiI6IjEzIn0.CMWX6a5AWovZJoayFN2dlnkI66G5Oo2TjHg9wvEziC4",
    "password": "654321"
}


### Check-token
POST {{urlLocal}}/check-token
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  
}

### Upload-photo
POST {{urlLocal}}/photo
Content-Type: multipart/form-data; boundary=MfnBoundry
Authorization: Bearer {{token}}

--MfnBoundry
Content-Disposition: form-data; name="title"

Título
--MfnBoundry
Content-Disposition: form-data; name="photo"; filename="imageNest.png"
Content-Type: image/png

< ./imageNest.png
--MfnBoundry--

### Upload-files
POST {{urlLocal}}/files
Content-Type: multipart/form-data; boundary=MfnBoundry
Authorization: Bearer {{token}}

--MfnBoundry
Content-Disposition: form-data; name="files"; filename="imageNest.png"
Content-Type: image/png

< ./imageNest.png

--MfnBoundry
Content-Disposition: form-data; name="files"; filename="imageNest1.png"
Content-Type: image/png

< ./imageNest1.png
--MfnBoundry--

### Upload-files-fields
POST {{urlLocal}}/files-field
Content-Type: multipart/form-data; boundary=MfnBoundry
Authorization: Bearer {{token}}

--MfnBoundry
Content-Disposition: form-data; name="documents"; filename="nestCommands.txt"
Content-Type: text/plain

< ./nestCommands.txt

--MfnBoundry
Content-Disposition: form-data; name="photos"; filename="imageNest.png"
Content-Type: image/png

< ./imageNest.png

--MfnBoundry
Content-Disposition: form-data; name="photos"; filename="imageNest.png"
Content-Type: image/png

< ./imageNest.png

--MfnBoundry
Content-Disposition: form-data; name="photos"; filename="imageNest1.png"
Content-Type: image/png

< ./imageNest1.png
--MfnBoundry--