### Local variable
@urlLocal = {{apiUrl}}/users
@contentType = application/json

### GET all
GET {{urlLocal}}

### GET one
# @prompt userId
GET {{urlLocal}}/{{userId}}

### POST
POST {{urlLocal}}
Content-Type: {{contentType}}

{
    "name": "example",
    "email": "example@provider.com",
    "password": "123456"
}

### POST
POST {{urlLocal}}
Content-Type: {{contentType}}

{
    "name": "example",
    "email": "example@provider.com",
    "password": "123456",
    "birthAt": "1990-06-18"
}

### PUT
# @prompt userId
PUT {{urlLocal}}/{{userId}}
Content-Type: {{contentType}}

{
    "name": "example4",
    "email": "example@provider.com",
    "password": "123456"
}

### PUT
# @prompt userId
PUT {{urlLocal}}/{{userId}}
Content-Type: {{contentType}}

{
    "name": "example4",
    "email": "example@provider.com",
    "password": "123456",
    "birthAt": "1990-06-18"
}

### PATCH
# @prompt userId
PATCH {{urlLocal}}/{{userId}}
Content-Type: {{contentType}}

{
    "name": "example"
}

### DELETE one
# @prompt userId
DELETE {{urlLocal}}/{{userId}}